### ISSUE TITLE
[Bug] Scroll not working

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#9] opened 2016-12-14 07:54 UTC
Even 100% scroll fail.

**Comment by xBuyax** [comment] 2016-12-14 13:39
Hi,

I will soon investigate this.
Is the bug only about scrolls failing?

**Comment by imbawind** [comment] 2016-12-14 14:43
Yeah, currently.

**Comment by xBuyax** [comment] 2016-12-14 15:33
Hi,
I confirmed it and found the issue: a code mistake in item data loading caused this, scrolls and maybe more wasn't loaded (properly).

I just commited a fix and to my tests scrolls work now.

Can you confirm this? I ask because this is a huge issue so I rather get confirmation.

**Comment by imbawind** [comment] 2016-12-14 16:17
Used gm command to make some scroll for magic att., seems to be working, some scrolls succeed, some scrolls failed.

**Comment by xBuyax** [comment] 2016-12-14 16:21
Ok, so now that it's fixed, I close this.

**Closed by xBuyax** 2016-12-14 16:21 UTC
Labels: bug
